= Data Preparation for Gen AI Applications
:navtitle: Home

== Introduction

This course equips students with the knowledge and practical skills to use **Docling** for efficiently converting and preparing unstructured document data for various AI tasks, particularly for fine-tuning Large Language Models (LLMs), and Retrieval Augmented Generation (RAG) applications. It also introduces the **Data Prep Kit** (DPK) project which is a collection of tools and libraries that help developers and data scientists prepare unstructured data for use in artificial intelligence (AI) applications.

**Target Audience:** Data scientists, AI engineers, solution architects, consultants, and developers who work with unstructured document data, and need to prepare it for AI model training, fine-tuning, or information retrieval.

**Duration:** 4 hours

== Objectives

On completing this course, you should be able to:

* Understand the challenges of unstructured document data and the role of Docling in addressing them.
* Install, configure, and use Docling via its Python API, web UI, and command line interface (CLI).
* Learn about conversion of various document formats (PDF, DOCX, HTML) into Docling's structured **DoclingDocument** format.
* Effectively navigate and utilize the **DoclingDocument** object to access text, layout, and metadata.
* Implement document chunking strategies using Docling to prepare data for LLMs.
* Learn about the different serialization techniques to convert documents into several output formats for downstream processing in AI applications.
* Be prepared to apply Docling to real-world document data preparation tasks.
* Integrate Docling into AI pipelines, particularly for **Retrieval Augmented Generation (RAG)** with frameworks like **LangChain** and vector databases like **Milvus**.
* Learn how the Data Prep Kit (DPK) can be used to train and fine-tune LLMs.

== Prerequisites

The following courses and labs are recommended before attempting this course:

* AI Fundamentals (https://training-lms.redhat.com/sso/saml/auth/rhlpint?RelayState=deeplinkoffering%3D62410986[Internal] | https://training-lms.redhat.com/sso/saml/auth/rhopen?RelayState=deeplinkoffering%3D62412150[Partner])

* Consult the https://source.redhat.com/career/start_learning/core_skills_academies/ai_skills_academy[AI Skills Academy] page for more introductory material on AI

* Introduction to Large Language Models (https://training-lms.redhat.com/sso/saml/auth/rhlpint?RelayState=deeplinkoffering%3D61705036[Internal] | https://training-lms.redhat.com/sso/saml/auth/rhopen?RelayState=deeplinkoffering%3D61706249[Partner])

* You must be comfortable with the basics of Python and usage of tools like `pip` to install liibraries

== Acknowledgements

* Karlos Knox
* Rutuja Deshmukh
* Rupali Talwatkar
* Sam Zahran
* Caitlyn Rymarchyk
* The Docling project maintainers. Many hands-on labs were adapted from the numerous detailed examples provided on the Docling website
* IBM team maintaining the Data Prep Kit for providing the hands-on labs for DPK
* Alain Airom (https://alain-airom.medium.com/) for writing loads of examples that the hands-on labs are based on
* Shivansh Kaushik (https://medium.com/@shivansh.kaushik) for the code in the RAG example
* Ravi Srinivasan
